"""Generated known-value scientific rasters. No NASA or upstream acquisition."""

import importlib.util
import json
from pathlib import Path
import tempfile
import unittest

import numpy as np
from osgeo import gdal

PILOT_PATH = Path(__file__).resolve().parents[2] / "scripts/raster-pilot/pilot.py"
spec = importlib.util.spec_from_file_location("raster_pilot", PILOT_PATH)
pilot = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pilot)


def fixture(directory, crs=3857, averaged_overviews=False):
    """A 512px parent crop with low/high radiance and a rejected-data hole."""
    values = np.full((512, 512), np.float32(0.12345679), dtype=np.float32)
    values[:256, 256:] = 1.5
    values[256:, :256] = 10000.25  # exceeds the old packed 6553.5 saturation
    values[256:, 256:] = 0
    values[32:64, 32:64] = -9999
    if averaged_overviews:
        values = (np.indices((512, 512)).sum(axis=0) % 2).astype(np.float32) * 1.5 + 0.25
    memory = gdal.GetDriverByName("MEM").Create("", 512, 512, 1, gdal.GDT_Float32)
    bounds = pilot.bbox(7, 37, 48)
    if crs == 4326:
        from osgeo import osr
        convert = osr.CoordinateTransformation(pilot.srs(3857), pilot.srs(4326))
        left, bottom, _ = convert.TransformPoint(bounds[0], bounds[1])
        right, top, _ = convert.TransformPoint(bounds[2], bounds[3])
        bounds = (left, bottom, right, top)
    memory.SetProjection(pilot.srs(crs).ExportToWkt())
    memory.SetGeoTransform((bounds[0], (bounds[2] - bounds[0]) / 512, 0,
                            bounds[3], 0, (bounds[1] - bounds[3]) / 512))
    band = memory.GetRasterBand(1)
    band.WriteArray(values)
    band.SetNoDataValue(-9999)
    band.SetUnitType(pilot.UNITS)
    if averaged_overviews:
        memory.BuildOverviews("AVERAGE", [2, 4])
    path = Path(directory) / "generated-not-nasa.tif"
    cog = gdal.GetDriverByName("COG").CreateCopy(str(path), memory,
        options=["COMPRESS=DEFLATE", "NUM_THREADS=1",
                 "OVERVIEWS=FORCE_USE_EXISTING" if averaged_overviews else "OVERVIEWS=NONE"])
    cog = None
    manifest = {"schema_version": 1, "kind": "synthetic-scientific-fixture",
                "product": "GENERATED-NOT-NASA", "semantics": "synthetic-radiance",
                "units": pilot.UNITS, "scale": 1, "offset": 0, "nodata": -9999,
                "crs": f"EPSG:{crs}", "input_filename": path.name, "input_sha256": pilot.sha256(path),
                "quality": {"policy": "rejected-to-nodata", "receipt": "Generated rejected-data hole."},
                "provenance": "Known values generated by test_pilot.py; not satellite observations."}
    manifest_path = Path(directory) / "manifest.json"
    manifest_path.write_text(json.dumps(manifest))
    return path, manifest_path, manifest, values


class RasterPilotTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.directory = Path(self.tmp.name)
        self.input, self.manifest_path, self.manifest, self.values = fixture(self.directory)

    def test_deterministic_bytes_and_receipt(self):
        first = pilot.render(self.manifest_path, self.input, self.directory / "one")
        second = pilot.render(self.manifest_path, self.input, self.directory / "two")
        self.assertEqual(first, second)
        files = sorted(p.relative_to(self.directory / "one") for p in (self.directory / "one").rglob("*") if p.is_file())
        self.assertEqual(len(files), 5)  # two PNGs, two science TIFFs, one receipt
        for name in files:
            self.assertEqual((self.directory / "one" / name).read_bytes(),
                             (self.directory / "two" / name).read_bytes())
        self.assertFalse(first["actual_nasa_data"])
        self.assertFalse(first["palette"]["upstream_style_verified"])
        self.assertIn("not-compared", first["tiles"][0]["parity"])

    def test_precision_nodata_and_parent_child_alignment(self):
        ds = pilot.validate_input(self.manifest, self.input)
        child = pilot.warp_science(ds, (8, 74, 96)).ReadAsArray()
        parent = pilot.warp_science(ds, (7, 37, 48)).ReadAsArray()
        np.testing.assert_array_equal(child, self.values[:256, :256])
        np.testing.assert_array_equal(child[1::2, 1::2], parent[:128, :128])
        self.assertEqual(parent[200, 30], np.float32(10000.25))
        self.assertEqual(parent[20, 20], -9999)
        self.assertEqual(child[100, 100], np.float32(0.12345679))
        rgba = pilot.colorize(child)
        self.assertEqual(rgba[40, 40].tolist(), [0, 0, 0, 0])
        self.assertEqual(rgba[100, 100, 3], 255)
        self.assertEqual(pilot.colorize(np.array([[0]], dtype=np.float32))[0, 0, 3], 255)

    def test_geographic_crop_reprojects_to_mercator(self):
        directory = self.directory / "geographic"
        directory.mkdir()
        path, _, manifest, _ = fixture(directory, 4326)
        ds = pilot.validate_input(manifest, path)
        out = pilot.warp_science(ds, (8, 74, 96))
        self.assertTrue(out.GetSpatialRef().IsSame(pilot.srs(3857)))
        self.assertEqual(out.RasterXSize, 256)
        self.assertEqual(out.ReadAsArray()[100, 100], np.float32(0.12345679))
        self.assertEqual(out.ReadAsArray()[40, 40], -9999)

    def test_averaged_cog_overviews_cannot_replace_native_scientific_samples(self):
        directory = self.directory / "averaged-overviews"
        directory.mkdir()
        path, _, manifest, values = fixture(directory, averaged_overviews=True)
        ds = pilot.validate_input(manifest, path)
        self.assertGreater(ds.GetRasterBand(1).GetOverviewCount(), 0)
        parent = pilot.warp_science(ds, (7, 37, 48)).ReadAsArray()
        np.testing.assert_array_equal(parent, values[1::2, 1::2])
        self.assertFalse(np.any(parent == 1.0))  # averaged overview values

    def test_pilot_geometry_crosses_original_geographic_granule_boundary(self):
        from osgeo import osr
        convert = osr.CoordinateTransformation(pilot.srs(3857), pilot.srs(4326))
        for tile in pilot.TILES:
            left, bottom, right, top = pilot.bbox(*tile)
            west, south, _ = convert.TransformPoint(left, bottom)
            east, north, _ = convert.TransformPoint(right, top)
            self.assertLess(south, 40)
            self.assertGreater(north, 40)
            self.assertGreater(west, -80)
            self.assertLess(east, -70)

    def test_locked_toolchain_has_scientific_input_and_output_drivers(self):
        for driver in ("HDF5", "COG", "GTiff", "PNG", "MEM"):
            with self.subTest(driver=driver):
                self.assertIsNotNone(gdal.GetDriverByName(driver))

    def test_multiple_unreceived_originals_cannot_claim_acquired_nasa_data(self):
        # Deliberately invalid/unreceived receipts, not real archive identities.
        # The impossible production timestamp is only a filename-syntax probe.
        names = [f"VNP46A4.A2019001.h10v{v:02d}.002.0000000000000.h5" for v in (4, 5)]
        manifest = dict(self.manifest, kind="nasa-black-marble", product="VNP46A4",
                        semantics="measured-nighttime-radiance", collection="002",
                        dataset="AllAngle_Composite_Snow_Free", product_url=pilot.PRODUCT_URL,
                        acquisition="2019", archives=[{"filename": name, "sha256": None,
                                                      "acquired_at": None} for name in names])
        self.manifest_path.write_text(json.dumps(manifest))
        originals = self.directory / "unreceived-originals"
        originals.mkdir()
        with self.assertRaisesRegex(ValueError, "missing original NASA archive"):
            pilot.render(self.manifest_path, self.input, self.directory / "phantom-nasa", originals)
        self.assertFalse((self.directory / "phantom-nasa").exists())
        manifest["archives"] = manifest["archives"] * 3
        with self.assertRaisesRegex(ValueError, "one to four"):
            pilot.validate_input(manifest, self.input, originals)

    def test_checksum_missing_bytes_and_template_fail_closed(self):
        self.manifest["input_sha256"] = "0" * 64
        with self.assertRaisesRegex(ValueError, "SHA-256 mismatch"):
            pilot.validate_input(self.manifest, self.input)
        self.input.unlink()
        with self.assertRaisesRegex(ValueError, "missing"):
            pilot.validate_input(self.manifest, self.input)
        template = Path(__file__).resolve().parents[2] / "data/raster-pilot/nasa-input.template.json"
        with self.assertRaises(ValueError):
            pilot.render(template, self.directory / "missing.tif", self.directory / "bad-output")
        self.assertFalse((self.directory / "bad-output").exists())

    def test_rejects_wrong_units_scaling_crs_quality_and_integer(self):
        for field, value in (("units", "styled byte"), ("scale", 0.1), ("crs", "EPSG:4326"),
                             ("quality", {"policy": "unchecked"}), ("kind", "falchi")):
            with self.subTest(field=field), self.assertRaises(ValueError):
                pilot.validate_input(dict(self.manifest, **{field: value}), self.input)
        integer = self.directory / "integer.tif"
        gdal.Translate(str(integer), str(self.input), format="COG", outputType=gdal.GDT_UInt16)
        manifest = dict(self.manifest, input_filename=integer.name, input_sha256=pilot.sha256(integer))
        with self.assertRaisesRegex(ValueError, "Float32"):
            pilot.validate_input(manifest, integer)

    def test_nodata_outside_crop_and_no_overwrite(self):
        ds = pilot.validate_input(self.manifest, self.input)
        outside = pilot.warp_science(ds, (8, 0, 0)).ReadAsArray()
        self.assertTrue(np.all(outside == -9999))
        output = self.directory / "existing"
        output.mkdir()
        with self.assertRaisesRegex(ValueError, "already exists"):
            pilot.render(self.manifest_path, self.input, output)

    def test_all_nodata_crop_is_not_a_successful_scientific_pilot(self):
        ds = gdal.Open(str(self.input))
        memory = gdal.GetDriverByName("MEM").CreateCopy("", ds)
        ds = None
        memory.GetRasterBand(1).Fill(-9999)
        self.input.unlink()
        gdal.GetDriverByName("COG").CreateCopy(str(self.input), memory,
            options=["OVERVIEWS=NONE"])
        self.manifest["input_sha256"] = pilot.sha256(self.input)
        self.manifest_path.write_text(json.dumps(self.manifest))
        with self.assertRaisesRegex(ValueError, "no valid scientific samples"):
            pilot.render(self.manifest_path, self.input, self.directory / "empty-result")
        self.assertFalse((self.directory / "empty-result").exists())

    def test_internal_mask_requires_explicit_normalized_nodata(self):
        ds = gdal.Open(str(self.input))
        memory = gdal.GetDriverByName("MEM").CreateCopy("", ds)
        ds = None
        band = memory.GetRasterBand(1)
        band.CreateMaskBand(gdal.GMF_PER_DATASET)
        mask = np.full((512, 512), 255, dtype=np.uint8)
        mask[100, 100] = 0  # still positive radiance: inconsistent handoff
        band.GetMaskBand().WriteArray(mask)
        self.input.unlink()
        gdal.GetDriverByName("COG").CreateCopy(str(self.input), memory,
            options=["OVERVIEWS=NONE"])
        self.manifest["input_sha256"] = pilot.sha256(self.input)
        with self.assertRaisesRegex(ValueError, "normalized to explicit nodata"):
            pilot.validate_input(self.manifest, self.input)

    def test_pixel_parity_measures_color_and_transparency(self):
        candidate = np.zeros((256, 256, 4), dtype=np.uint8)
        candidate[0, 0] = (10, 20, 30, 255)
        reference = candidate.copy()
        self.assertEqual(pilot.compare_pixels(candidate, reference)["rgb_mismatch_pixels"], 0)
        reference[0, 0, 0] = 16
        reference[0, 1, 3] = 255
        report = pilot.compare_pixels(candidate, reference)
        self.assertEqual(report["alpha_mismatch_pixels"], 1)
        self.assertEqual(report["rgb_mismatch_pixels"], 1)
        self.assertEqual(report["mean_absolute_channel_error_shared_visible"], 2.0)
        self.assertEqual(report["max_channel_error_shared_visible"], 6)

    def test_reference_handoff_integrity_and_rendered_comparison(self):
        out = self.directory / "reference"
        receipt = pilot.render(self.manifest_path, self.input, out)
        references = {"kind": "synthetic-fixture", "layer": "PostGIS:VIIRS_2019", "captured_at": "SYNTHETIC-NOT-UPSTREAM",
                      "crs": "EPSG:3857", "tiles": {}}
        for tile, row in zip(pilot.TILES, receipt["tiles"]):
            key = "/".join(map(str, tile))
            references["tiles"][key] = {"filename": key + ".png", "bbox": row["bbox"],
                                        "width": 256, "height": 256, "sha256": row["png_sha256"]}
        path = out / "reference.json"
        path.write_text(json.dumps(references))
        comparison = pilot.render(self.manifest_path, self.input, self.directory / "compared", reference_path=path)
        for row in comparison["tiles"]:
            self.assertEqual(row["parity"]["alpha_mismatch_pixels"], 0)
            self.assertEqual(row["parity"]["rgb_mismatch_pixels"], 0)
        references["tiles"]["8/74/96"]["bbox"] = [0, 0, 1, 1]
        path.write_text(json.dumps(references))
        with self.assertRaisesRegex(ValueError, "bbox mismatch"):
            pilot.render(self.manifest_path, self.input, self.directory / "bad-reference", reference_path=path)
        self.assertFalse((self.directory / "bad-reference").exists())

    def test_indexed_reference_retains_palette_transparency(self):
        memory = gdal.GetDriverByName("MEM").Create("", 256, 256, 1, gdal.GDT_Byte)
        indices = np.ones((256, 256), dtype=np.uint8)
        indices[0, 0] = 0
        memory.GetRasterBand(1).WriteArray(indices)
        table = gdal.ColorTable()
        table.SetColorEntry(0, (0, 0, 0, 0))
        table.SetColorEntry(1, (10, 20, 30, 255))
        memory.GetRasterBand(1).SetColorTable(table)
        memory.GetRasterBand(1).SetColorInterpretation(gdal.GCI_PaletteIndex)
        path = self.directory / "indexed.png"
        gdal.GetDriverByName("PNG").CreateCopy(str(path), memory)
        rgba = pilot.read_png(path)
        self.assertEqual(rgba[0, 0].tolist(), [0, 0, 0, 0])
        self.assertEqual(rgba[1, 1].tolist(), [10, 20, 30, 255])

    def test_received_wms_url_binds_geometry_and_refuses_extra_parameters(self):
        from urllib.parse import urlencode
        params = {"service": "WMS", "version": "1.1.1", "request": "GetMap",
                  "layers": "PostGIS:VIIRS_2019", "styles": "", "format": "image/png",
                  "transparent": "true", "srs": "EPSG:3857", "width": "256", "height": "256",
                  "bbox": ",".join(str(value) for value in pilot.bbox(8, 74, 96))}
        url = "https://www2.lightpollutionmap.info/geoserver/gwc/service/wms?" + urlencode(params)
        pilot.validate_reference_url(url, (8, 74, 96))
        with self.assertRaisesRegex(ValueError, "bbox mismatch"):
            pilot.validate_reference_url(url, (7, 37, 48))
        with self.assertRaisesRegex(ValueError, "unexpected"):
            pilot.validate_reference_url(url + "&unreviewed=1", (8, 74, 96))


if __name__ == "__main__":
    unittest.main()
